"""Update Book Table

Revision ID: 4d24dd8244de
Revises: 8cd57bee0e11
Create Date: 2026-03-22 23:15:12.914822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d24dd8244de'
down_revision: Union[str, Sequence[str], None] = '8cd57bee0e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('language', sa.String(), nullable=False))
    op.drop_column('books', 'languahe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('languahe', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('books', 'language')
    # ### end Alembic commands ###
