"""Add Book Table

Revision ID: 8cd57bee0e11
Revises: 9de87e4d3999
Create Date: 2026-03-22 23:03:40.904525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd57bee0e11'
down_revision: Union[str, Sequence[str], None] = '9de87e4d3999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('languahe', sa.String(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('annotation', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
